id: d9565f8c-dbc2-4bb5-9597-d0f066094f1f
creation_dt: 2024-02-12T12:00:00
product: { name: chuk_landwater }
product_type: chuk_landwater
platform: {code: bbb}
instrument: {name: ccc}
format: {name: NetCDFX}
extent:
  coord:
    ll: {lat: 47.01322552502985, lon: -16.7980635849523}
    lr: {lat: 47.01322552502985, lon: 5.659063256444921}
    ul: {lat: 61.71634739697962, lon: -16.7980635849523}
    ur: {lat: 61.71634739697962, lon: 5.659063256444921}
  from_dt: 2019-01-01T12:00:00
  center_dt: 2021-01-01T12:00:00
  to_dt: 2022-12-31T12:00:00
grid_spatial:
  projection:
    geo_ref_points:
      ll: { x: -332000, y: -267000 }
      lr: { x: 765000, y: -267000 }
      ul: { x: -332000, y: 1250000 }
      ur: { x: 765000, y: 1250000 }
    spatial_reference: "EPSG:27700"
image:
  bands:
    lake_mask:
      path: /data/chuk/d1.1-land_water.nc
      layer: lake_mask
    landwater:
      path: /data/chuk/d1.1-land_water.nc
      layer: landwater
    rivers:
      path: /data/chuk/d1.1-land_water.nc
      layer: rivers
lineage:
  source_datasets: {}