id: 11eb12d5-fe20-480c-8aed-978d850c0ee4
creation_dt: 2023-08-25T12:00:00
product: { name: chuk_maxst }
product_type: chuk_maxst
platform: {code: bbb}
instrument: {name: ccc}
format: {name: NetCDFX}
extent:
  coord:
    ll: {lat: -48, lon: -5}
    lr: {lat: -48, lon: 12}
    ul: {lat: 62, lon: -5}
    ur: {lat: 62, lon: 12}
  from_dt: 2019-01-01T12:00:00
  center_dt: 2021-01-01T12:00:00
  to_dt: 2022-12-31T12:00:00
grid_spatial:
  projection:
    geo_ref_points:
      ll: {x: -398000, y: -267000}
      lr: {x: 80700, y: -267000}
      ul: {x: -398000, y: 1315000}
      ur: {x: 80700, y: 1315000}
    spatial_reference: "EPSG:27700"
image:
  bands:
    ST:
      path: /data/chuk/maxst.nc
      layer: "ST"
lineage:
  source_datasets: {}